### ISSUE TITLE
Sing-box for Android PuerNya版本

### ISSUE THREAD

**Issue by Dormxb** [DustinWin/clash_singbox-tutorials#12]
你好，
    请问哪里可以下载这个作者修改的[sing-box](https://github.com/PuerNya/)，感谢

**Comment by DustinWin** [comment]
> 你好， 请问哪里可以下载这个作者修改的[sing-box](https://github.com/PuerNya/)，感谢

我的另一个项目里就有。https://github.com/DustinWin/clash_singbox-tools

**Comment by Dormxb** [comment]
不好意思我提问的有问题，是这个作者修改的sing-box for android版本

**Comment by DustinWin** [comment]
> 不好意思我提问的有问题，是这个作者修改的sing-box for android版本

进入 https://github.com/PuerNya/sing-box/actions/workflows/sfa.yml ，点击最新的“Multi Builds”，里面就可以下载了。

**Comment by Dormxb** [comment]
感谢
