### ISSUE TITLE
机场提供者重启的时候不会自动更新

### ISSUE THREAD

**Issue by happyhaha1** [DustinWin/clash_singbox-tutorials#13]
<img width="733" alt="image" src="https://github.com/DustinWin/clash_singbox-tutorials/assets/10184254/4daa1fc6-47d3-4977-a15f-3ed7efff4cd0">
每次 crash 重启，由于提供者没更新，导致无法使用

**Comment by DustinWin** [comment]
机场订阅链接可能被墙。
