### ISSUE TITLE
sfa启动问题与节点选择问题

### ISSUE THREAD

**Issue by YoloBird** [DustinWin/clash_singbox-tutorials#15]
大佬你好，我下载了搭载 sing-box PuerNya 版内核的 sing-box for Android，是最新的1.90.rc3的，但是我在使用的时候遇到了一点问题。
第一个是每次启动都很慢，正如您在教程中所说的，如果配置文件不在本地，那么每次启动都要重新加载，但是使用的sfa我去哪里找singbox的根目录并且创建providers呢？还是我手机的根目录就可以？

第二个问题，不知道您使用时有没有遇到过，那就是重新启动后他不会记住我之前的节点选择状态，可能也是因为远程订阅没在本地，但等一会儿加载出来之后，我发现点击有的节点会出现下面的问题
![Screenshot_2024-04-11-21-28-22-956_io.nekohasekai.sfa.jpg](https://github.com/DustinWin/clash_singbox-tutorials/assets/112264701/4de8c0d5-0cf6-4bf6-804c-e390fc12b1c8)

，而且我打开sfa之后还是没办法代理，哪怕我选择的是全局模式，全局模式里选择了我可以ping出延迟的节点。

谢谢大佬

**Comment by YoloBird** [comment]
大佬你好，我已经解决了第一个问题，找到了根目录并且看到里面多了我的yaml订阅文件和远程规则，并且已经能够快速启动，但是第二个问题还是存在，这个outbound的问题

**Comment by YoloBird** [comment]
https://gist.githubusercontent.com/YoloBird/48e4319b6a934251f831ec25f74de70c/raw/gistfile1.txt

以上是我的配置文件

**Comment by DustinWin** [comment]
手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。

**Comment by YoloBird** [comment]
> 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。

第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了

**Comment by DustinWin** [comment]
> > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> 
> 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了

v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。

**Comment by YoloBird** [comment]
> > > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> > 
> > 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了
> 
> v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。

不兼容吗？我导入订阅用起来还行我一会儿鼓捣一下规则吧。
使用面板更换节点是什么意思

**Comment by DustinWin** [comment]
> > > > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> > > 
> > > 
> > > 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了
> > 
> > 
> > v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。
> 
> 不兼容吗？我导入订阅用起来还行我一会儿鼓捣一下规则吧。 使用面板更换节点是什么意思

浏览器打开 127.0.0.1:9090/ui

**Comment by YoloBird** [comment]
> > > > > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> > > > 
> > > > 
> > > > 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了
> > > 
> > > 
> > > v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。
> > 
> > 不兼容吗？我导入订阅用起来还行我一会儿鼓捣一下规则吧。 使用面板更换节点是什么意思
> 
> 浏览器打开 127.0.0.1:9090/ui

感谢大佬，原来还有面板。我去换到1.9.0试一试。

**Comment by YoloBird** [comment]
> > > > > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> > > > 
> > > > 
> > > > 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了
> > > 
> > > 
> > > v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。
> > 
> > 不兼容吗？我导入订阅用起来还行我一会儿鼓捣一下规则吧。 使用面板更换节点是什么意思
> 
> 浏览器打开 127.0.0.1:9090/ui

这是哪里发布的使用教程？面板之类的使用方法从来没见过

**Comment by DustinWin** [comment]
> > > > > > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> > > > > 
> > > > > 
> > > > > 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了
> > > > 
> > > > 
> > > > v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。
> > > 
> > > 
> > > 不兼容吗？我导入订阅用起来还行我一会儿鼓捣一下规则吧。 使用面板更换节点是什么意思
> > 
> > 
> > 浏览器打开 127.0.0.1:9090/ui
> 
> 这是哪里发布的使用教程？面板之类的使用方法从来没见过

这个用不着教程啊。

**Comment by YoloBird** [comment]
> > > > > > > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> > > > > > 
> > > > > > 
> > > > > > 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了
> > > > > 
> > > > > 
> > > > > v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。
> > > > 
> > > > 
> > > > 不兼容吗？我导入订阅用起来还行我一会儿鼓捣一下规则吧。 使用面板更换节点是什么意思
> > > 
> > > 
> > > 浏览器打开 127.0.0.1:9090/ui
> > 
> > 这是哪里发布的使用教程？面板之类的使用方法从来没见过
> 
> 这个用不着教程啊。

我表述错了，我的意思是以前不知道sing-box的这个ui功能

**Comment by DustinWin** [comment]
> > > > > > > > 手动在 sfa 根目录新建“providers”和“ruleset”文件夹后试试，另外文件名不建议用中文。
> > > > > > > 
> > > > > > > 
> > > > > > > 第二个问题解决了，应该是版本bug，我使用了1.8.5的版本解决了问题，1.8.9以及之后的1.9.0因为groups的ui发生了变化，所以应该是出现了bug，只能等慢慢修复了
> > > > > > 
> > > > > > 
> > > > > > v1.9.0 以下的版本不要使用我的规则集，不兼容。可以使用面板去更换节点啊。
> > > > > 
> > > > > 
> > > > > 不兼容吗？我导入订阅用起来还行我一会儿鼓捣一下规则吧。 使用面板更换节点是什么意思
> > > > 
> > > > 
> > > > 浏览器打开 127.0.0.1:9090/ui
> > > 
> > > 
> > > 这是哪里发布的使用教程？面板之类的使用方法从来没见过
> > 
> > 
> > 这个用不着教程啊。
> 
> 我表述错了，我的意思是以前不知道sing-box的这个ui功能

sing-box wiki 里有，多看文档。
