### ISSUE TITLE
      "excludes": "高倍|×10",       "download_ua": "clash.meta",

### ISSUE THREAD

**Issue by onlyfirer** [DustinWin/clash_singbox-tutorials#17]
最新的这个sing-boxpx，不能读两个命令

**Comment by DustinWin** [comment]
> 最新的这个sing-boxpx，不能读两个命令

具体版本是多少，报错内容呢？

**Comment by onlyfirer** [comment]
![1](https://github.com/DustinWin/clash_singbox-tutorials/assets/94467799/04e3e446-c29a-440c-a1ba-ea09833181ac)
![2](https://github.com/DustinWin/clash_singbox-tutorials/assets/94467799/08ec84af-642a-4dff-8ba5-a67d0d817efc)
我删除config.json中方框中的那两行就可以启动！

**Comment by DustinWin** [comment]
> ![1](https://private-user-images.githubusercontent.com/94467799/325034394-04e3e446-c29a-440c-a1ba-ea09833181ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzA4NTMsIm5iZiI6MTcxMzkzMDU1MywicGF0aCI6Ii85NDQ2Nzc5OS8zMjUwMzQzOTQtMDRlM2U0NDYtYzI5YS00NDBjLWExYmEtZWEwOTgzMzE4MWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAzNDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MmE0YjBmMDJjOGI5NmJlNDY3ODM4ZTQyZGQyMTM5ZjM5YTNlYWNmYTA0YjRjZWQ4MDQ1MmY1OTM1OTRjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRXJTTtlbvAiCHd4OWW76gOI7yoxChhKnD2eIlLQn5Q) ![2](https://private-user-images.githubusercontent.com/94467799/325034400-08ec84af-642a-4dff-8ba5-a67d0d817efc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzA4NTMsIm5iZiI6MTcxMzkzMDU1MywicGF0aCI6Ii85NDQ2Nzc5OS8zMjUwMzQ0MDAtMDhlYzg0YWYtNjQyYS00ZGZmLThiYTUtYTY3ZDBkODE3ZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAzNDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4M2M1YWY4YzNhZjdjMmEwYjhhMWM0NzRjOTBhMTYzNDM0NzVkYjllNGQ0OTNiYzg5YjIwNTRlMDM0YWMyYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2h__dGUT-CDmHy0tpdWdxhyLlSW04XcnHUR5vEB8nz0) 我删除config.json中方框中的那两行就可以启动！ ![2](https://private-user-images.githubusercontent.com/94467799/325035583-b4762410-5766-4d14-a452-8feffd2eef87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzA4NTMsIm5iZiI6MTcxMzkzMDU1MywicGF0aCI6Ii85NDQ2Nzc5OS8zMjUwMzU1ODMtYjQ3NjI0MTAtNTc2Ni00ZDE0LWE0NTItOGZlZmZkMmVlZjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAzNDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWEzNzI0Zjg4MDM2ZDI0MDdlODEyNzUxY2UzZTc1YjE3ZjkwYmVjODgwZTJhMzg3MzJmMDEwZmJiM2VkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.56iSH0Pwfhpbin7k6YXRd8Conyy1Ium7HKtMuEk2VaM)

你的节点名称里有这两个参数里面的关键字吗？

**Comment by DustinWin** [comment]
我叫你发内核版本你也不发，ShellCrash 里面的 sing-boxp 核并不是最新版。

**Comment by onlyfirer** [comment]
{ "tag": "📈 网络测试", "type": "selector", "outbounds": [ "🎯 全球直连", "🇭🇰 香港节点", "🇳🇱 荷兰节点", "🇯🇵 日本节点",  "🇸🇬 新加坡节点", "🇺🇸 美国节点" ] },
用了这些关键字

**Comment by onlyfirer** [comment]
内核版本是1.8.5-73d97226

**Comment by DustinWin** [comment]
> 内核版本是1.8.5-73d97226

很明显这不是最新版，按照这个 https://github.com/DustinWin/clash_singbox-tools 更新一下。
