### ISSUE TITLE
rule-set规则集，连接都命中走了final

### ISSUE THREAD

**Issue by popolife** [DustinWin/clash_singbox-tutorials#18]
@DustinWin 大佬，昨晚更新规则集过后，出现了这个问题，参考了singbox rule-set分享篇

**Comment by DustinWin** [comment]
不懂

**Comment by popolife** [comment]
> 不懂

之前本应该命中的链接，例如油管谷歌，之前正常出站是代理域名，现在都无法命中规则走了漏网之鱼。

**Comment by DustinWin** [comment]
> > 不懂
> 
> 之前本应该命中的链接，例如油管谷歌，之前正常出站是代理域名，现在都无法命中规则走了漏网之鱼。

贴完整配置。

**Comment by popolife** [comment]
> > > 不懂
> > 
> > 
> > 之前应该命中的链接，例如油管谷歌，之前正常出站是代理域名，现在都无法命中规则走了漏网之鱼。
> 
> 贴完整配置。

完全参考了这篇教程进行的配置[分享自己使用[ShellCrash](https://github.com/juewuy/ShellCrash)配置rule_set方案的一套配置](https://github.com/DustinWin/clash_singbox-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/sing-box/%E5%88%86%E4%BA%AB%E7%AF%87/%E5%88%86%E4%BA%AB%E8%87%AA%E5%B7%B1%E4%BD%BF%E7%94%A8%20ShellCrash%20%E6%90%AD%E9%85%8D%20rule_set%20%E6%96%B9%E6%A1%88%E7%9A%84%E4%B8%80%E5%A5%97%E9%85%8D%E7%BD%AE.md)，大佬还需要提供什么配置信息吗？

**Comment by DustinWin** [comment]
> > > > 不懂
> > > 
> > > 
> > > 之前应该命中的链接，例如油管谷歌，之前正常出站是代理域名，现在都无法命中规则走了漏网之鱼。
> > 
> > 
> > 贴完整配置。
> 
> 完全是按照这篇教程进行的配置[分享自己使用ShellCrash配置rule_set方案的一套配置](https://github.com/DustinWin/clash_singbox-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/sing-box/%E5%88%86%E4%BA%AB%E7%AF%87/%E5%88%86%E4%BA%AB%E8%87%AA%E5%B7%B1%E4%BD%BF%E7%94%A8%20ShellCrash%20%E6%90%AD%E9%85%8D%20rule_set%20%E6%96%B9%E6%A1%88%E7%9A%84%E4%B8%80%E5%A5%97%E9%85%8D%E7%BD%AE.md)，大佬还需要提供什么配置信息吗？

你再重试一下，可能规则集当时正在构建。

**Comment by DustinWin** [comment]
感谢反馈，已修复。

**Comment by popolife** [comment]
> @DustinWin更新 sing-box PuerNya 版本至 v1.9.0-rc.22-8fd2d823后dns.json文件校验失败。 启动内核服务后提示： FATAL[0000] decrypt config at /tmp/ShellCrash/jsons/cust_dns.json: yaml: line 17: did not find expected key 自定义配置文件校验失败，请检查【/data/ShellCrash/jsons/dns.json】文件！ 尝试使用基础配置文件启动~

大佬求指教

**Comment by DustinWin** [comment]
sing-boxp 核最新版有较大改动，今晚更新教程。

**Comment by popolife** [comment]
> sing-boxp 核最新版有较大调整，今晚更新教程。

明白!

**Comment by DustinWin** [comment]
> > sing-boxp 核最新版有较大调整，今晚更新教程。
> 
> 明白!



> > sing-boxp 核最新版有较大调整，今晚更新教程。
> 
> 明白!

重新导入配置文件就可以了。
