### ISSUE TITLE
按教程安装了crash和adg，发现有个docker容器无法使用

### ISSUE THREAD

**Issue by kunnyl** [DustinWin/clash_singbox-tutorials#19]
**crash版本：**
1.9.0release

**docker容器：**
boredazfcuk/icloudpd 
container for icloud_photo_downloader  https://github.com/boredazfcuk/docker-icloudpd

**容器错误log：**
…
2024-05-2 00:01:06 DEBUG LAN IP Address: 172.17.0.5
2024-05-2 00:01:06 DEBUG Default gateway: 172.17.0.1
2024-05-2 00:01:06 DEBUG DNS server: 192.168.100.1
2024-04-2 00:01:07 DEBUG IP address for icloud.com.cn: 103.115.248.1
2024-05-2 00:01:12 ERROR No route to icloud.com.cn found. Please check your container's network settings - exiting
2024-05-2 00:01:12 ERROR Error debug - traceroute: bad address 'icloud.com.cn'
...

**交叉对比验证**
1，关闭crash服务，docker运行正常
2，开启crash服务，docker报错，必现

PS：五一重新安装了crash，之前好像没这个问题，请帮忙告知此类问题应该如何定位解决

**Comment by DustinWin** [comment]
具体参考的哪个教程？

**Comment by kunnyl** [comment]
教程合集/Clash/全网最详细的解锁 SSH ShellCrash 搭配 AdGuardHome 安装和配置教程-Clash 方案.md
mihomo 内核的这个！

**Comment by kunnyl** [comment]
> 具体参考的哪个教程？

教程合集/Clash/全网最详细的解锁 Shellcrush 搭配 Adguardholm 安装和配置教程-Clash 方案.MD
Mihomo 内核的这个。
相同网络下icloud.com.cn电脑端可以正常访问

**Comment by DustinWin** [comment]
> > 具体参考的哪个教程？
> 
> 教程合集/Clash/全网最详细的解锁 Shellcrush 搭配 Adguardholm 安装和配置教程-Clash 方案.MD Mihomo 内核的这个。 相同网络下icloud.com.cn电脑端可以正常访问

你看这篇吧，https://github.com/DustinWin/clash_singbox-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/sing-box/%E5%88%86%E4%BA%AB%E7%AF%87/%E5%88%86%E4%BA%AB%E8%87%AA%E5%B7%B1%E4%BD%BF%E7%94%A8%20ShellCrash%EF%BC%88fakeip%20%E6%A8%A1%E5%BC%8F%EF%BC%89%E6%90%AD%E9%85%8D%20AdGuardHome%20%E7%9A%84%E4%B8%80%E5%A5%97%E9%85%8D%E7%BD%AE.md
