### ISSUE TITLE
Mihomo希望增加 ip-asn的订阅配置 

### ISSUE THREAD

**Issue by crackerfly** [DustinWin/clash_singbox-tutorials#20]
Mihomo 1.18.3 开始正式支持了 IP-ASN规则 
https://wiki.metacubex.one/config/rules/

作为cn-ip的补充，在surge上实测半年效果非常好， 希望在Mihomo的分享配置中增加此项  

https://github.com/missuo/ASN-China

https://github.com/VirgilClyne/GetSomeFries/wiki/%F0%9F%8C%90-ASN

**Comment by DustinWin** [comment]
刚好增加了，有特殊需求可 fork 项目后自行添加。
