### ISSUE TITLE
Geosite 已废弃且可能在不久的将来移除？

### ISSUE THREAD

**Issue by gzxiexl** [DustinWin/clash_singbox-tutorials#21]
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/40417977/a92d0813-0ab9-4a5f-96ff-c735c076bb36)
#

是否需要切换到其他？

**Comment by DustinWin** [comment]
目前还没彻底删除对 geodata 的支持，就算到时删除了也不要紧，用的是 PuerNya 的内核。

**Comment by Perter1999** [comment]
> 目前还没彻底删除对 geodata 的支持，就算到时删除了也不要紧，用的是 PuerNya 的内核。

大佬，那geodate文件还会更新吗？我是按基础教程下载的。https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.db还要ip.db

**Comment by DustinWin** [comment]
> > 目前还没彻底删除对 geodata 的支持，就算到时删除了也不要紧，用的是 PuerNya 的内核。
> 
> 大佬，那geodate文件还会更新吗？我是按基础教程下载的。[https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.db还要ip.db](https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.db%E8%BF%98%E8%A6%81ip.db)

每天都在更新。
