### ISSUE TITLE
红米AX6000固件版本疑问

### ISSUE THREAD

**Issue by arrowing** [DustinWin/clash_singbox-tutorials#22]
最近买了这个路由器，开了 shellcrash 发现网速不是很快，去掉就快了，不晓得是什么问题，猜测大概率是DNS的问题。
所以网上找下相关配置就找到这来啦。

发现该教程的固件版本有个疑问：
我看了官网的固件下载界面，好像没有这个版本，最新的是 1.0.67 版本哦
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/9293244/af299c27-e6e1-4de1-8812-e53d78ee92f0)

**Comment by DustinWin** [comment]
官方群（现为非官方了）里有这个版本，区别不大。

**Comment by arrowing** [comment]
> 官方群（现为非官方了）里有这个版本，区别不大。

好的，谢谢
