### ISSUE TITLE
向日葵远程连不上

### ISSUE THREAD

**Issue by shihaoZheng** [DustinWin/clash_singbox-tutorials#24]
使用了最新的ShellCrash（fakeip 模式）搭配 AdGuardHome，但是向日葵远程软件连接不上服务器，大佬这个怎么设置解决

**Comment by DustinWin** [comment]
把本地的 `dns` 配置 copy 出来，发一下。

**Comment by shihaoZheng** [comment]
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/a3d6a489-7571-4243-9a10-467839658b46)
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/ff570674-a01b-4a2c-a09d-3219724bc883)
是这个吗

**Comment by DustinWin** [comment]
需要添加 `oray.com` 域名到 fakeip-filter，已经提交等合并（https://github.com/juewuy/ShellCrash/pull/658），或者自行添加。
