### ISSUE TITLE
Shellcrash里面，Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗

### ISSUE THREAD

**Issue by ixbcqq** [DustinWin/clash_singbox-tutorials#27]
Shellcrash里面，Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗

**Comment by DustinWin** [comment]
目前来说，在 mihomo 内核里，`dns` 设置中的 `fake-ip-filter: ['+.*']` 属于 `redir-host` 模式；在 sing-box 里，`dns.rules` 中走国内 dns 的为 redir-host 模式。所以关键在于你的 dns 配置。

**Comment by ixbcqq** [comment]
> 目前来说，在 mihomo 内核里，`dns` 设置中的 `fake-ip-filter: ['+.*']` 属于 `redir-host` 模式；在 sing-box 里，`dns.rules` 中走国内 dns 的为 redir-host 模式。所以关键在于你的 dns 配置。

感谢回复哈，我问了作者，他说clash基础内核已移除redirhost支持，那我就不折腾了

**Comment by DustinWin** [comment]
> > 目前来说，在 mihomo 内核里，`dns` 设置中的 `fake-ip-filter: ['+.*']` 属于 `redir-host` 模式；在 sing-box 里，`dns.rules` 中走国内 dns 的为 redir-host 模式。所以关键在于你的 dns 配置。
> 
> 感谢回复哈，我问了作者，他说clash基础内核已移除redirhost支持，那我就不折腾了

通过上述方法也可以实现 `redir-host` 效果。
