### ISSUE TITLE
sing-box这段配置是哪来的呢？我在官方文档也没找到啊？

### ISSUE THREAD

**Issue by MiniKoro** [DustinWin/clash_singbox-tutorials#29]
```
"outbound_providers": [
    {
      "tag": "🛫 我的机场",
      "type": "remote",
      // 修改为你的 Clash 订阅链接
      "download_url": "https://example.com/xxx/xxx&flag=clash",
      "path": "./providers/airport.yaml",
      "download_interval": "24h",
      "download_ua": "clash.meta",
      "includes": [ "🇭🇰|🇹🇼|🇯🇵|🇰🇷|🇸🇬|🇺🇸" ],
      "healthcheck_url": "https://www.gstatic.com/generate_204",
      "healthcheck_interval": "10m"
    }
  ]
```

**Comment by DustinWin** [comment]
我不是标明了是 sing-box PuerNya 版内核吗？

**Comment by kzlong** [comment]
> 我不是标明了是 sing-box PuerNya 版内核吗？

请教下我想把配置中分地区这部分替换成显示所有节点，要怎么修改，我尝试修改成"all"和"*"都是提示报dependency not found for outbound

    { "tag": "🚀 节点选择", "type": "selector", "outbounds": [ "🇭🇰 香港节点", "🆓 免费节点", "🇹🇼 台湾节点", "🇯🇵 日本节点", "🇰🇷 韩国节点", "🇸🇬 新加坡节点", "🇺🇸 美国节点" ] },
===》{ "tag": "🚀 节点选择", "type": "selector", "outbounds": "*" },

**Comment by DustinWin** [comment]
> > 我不是标明了是 sing-box PuerNya 版内核吗？
> 
> 请教下我想把配置中分地区这部分替换成显示所有节点，要怎么修改，我尝试修改成"all"和"*"都是提示报dependency not found for outbound
> 
> ```
> { "tag": "🚀 节点选择", "type": "selector", "outbounds": [ "🇭🇰 香港节点", "🆓 免费节点", "🇹🇼 台湾节点", "🇯🇵 日本节点", "🇰🇷 韩国节点", "🇸🇬 新加坡节点", "🇺🇸 美国节点" ] },
> ```
> 
> ===》{ "tag": "🚀 节点选择", "type": "selector", "outbounds": "*" },

很明显你没有看文档，不能想当然地自己去修改。
```
{ "tag": "🚀 节点选择", "type": "selector", "outbounds": [ "所有节点" ] },
{ "tag": "所有节点", "type": "urltest", "tolerance": 50, "use_all_providers": true }
```
