### ISSUE TITLE
红米ax6000内存及定时任务自动更新内核疑问

### ISSUE THREAD

**Issue by Wil1em** [DustinWin/clash_singbox-tutorials#30]
大佬好，想问下在最新的分享篇中[“分享自己使用 ShellCrash（fakeip 模式）搭配 AdGuardHome的一套配置“](https://github.com/DustinWin/clash_singbox-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/sing-box/%E5%88%86%E4%BA%AB%E7%AF%87/%E5%88%86%E4%BA%AB%E8%87%AA%E5%B7%B1%E4%BD%BF%E7%94%A8%20ShellCrash%EF%BC%88fakeip%20%E6%A8%A1%E5%BC%8F%EF%BC%89%E6%90%AD%E9%85%8D%20AdGuardHome%20%E7%9A%84%E4%B8%80%E5%A5%97%E9%85%8D%E7%BD%AE.md)：
1. 使用shellclash(rule-set)+adguardhome方案内存够用吗，不会出现内存过载自动重启的情况嘛，之前配置的时候运行一两个小时左右就会过载重启了，虽然之前没有使用lite版的dns.json文件而是使用了防止dns泄露教程里的(可能是那个文件的dns缓存的问题？)，所以想问下您使用该最新分享篇的配置的时候内存是否够用，没有内存问题的话我也使用这个方案
2. 另外定时任务自动更新sing-box_PuerNya版内核时貌似不会成功(使用task.user的代码如下)，大佬有遇到该问题嘛
`201#curl -o /data/ShellCrash/CrashCore.tar.gz -L https://raw.githubusercontent.com/DustinWin/clash_singbox-tools/main/sing-box-puernya/sing-box-linux-armv8.tar.gz && /data/ShellCrash/start.sh restart >/dev/null 2>&1#更新sing-box_PuerNya版内核`
![2](https://github.com/DustinWin/clash_singbox-tutorials/assets/152229984/72a9312b-ed88-4357-8026-17025c2ccd70)

**Comment by DustinWin** [comment]
1. 之前我测试过，路由器意外重启并不是因为运存或 CPU 过载，而是连接数（可在面板主页查看）达到一定数量（大于 500 就会出现卡顿的情况）后导致。解决方法是在 dns.json 的 `dns.rules` 中使 `cn` 走国内 dns，然后在 shellcrash 里选择 mix 模式，开启绕过 cn_ip
2. 必须在启动服务的情况下执行，否则可以在 `https://raw.githubusercontent.com` 地址前面加上 `https://mirror.ghproxy.com/` 进行反代

**Comment by Wil1em** [comment]
> 1. 之前我测试过，路由器意外重启并不是因为运存或 CPU 过载，而是连接数（可在面板主页查看）达到一定数量（大于 500 就会出现卡顿的情况）后导致。解决方法是在 dns.json 的 `dns.rules` 中使 `cn` 走国内 dns，然后在 shellcrash 里选择 mix 模式，开启绕过 cn_ip
> 2. 必须在启动服务的情况下执行，否则可以在 `https://raw.githubusercontent.com` 地址前面加上 `https://mirror.ghproxy.com/` 进行反代

确实有用，多谢大佬
