### ISSUE TITLE
关于小米BE6500Pro是否满足ShellCrash 搭配 AdGuardHome 安装和配置教程-sing-box 方案的配置要求

### ISSUE THREAD

**Issue by NJYZ-96** [DustinWin/clash_singbox-tutorials#31]
![截图_20240626080350](https://github.com/DustinWin/clash_singbox-tutorials/assets/125748593/47b19363-74eb-499f-af50-7106df244c69)
小米BE6500Pro安装ShellCrash 之后可用空间就不大了，不清楚是否满足 AdGuardHome 的安装需求；
建议能否把AdGuardHome对空间的需求明确到教程中？
如果空间需求不满足，BE6500Pro处理器性能和内存还是蛮好的，是否有其它扩展空间的方案？
产品名称Xiaomi 路由器 BE6500 Pro
处理器 高通IPQ5322四核A53最高1.5G
1GB内存+512MB存储

**Comment by DustinWin** [comment]
这路由器的分区也是 6（*/data* 目录太小了），试试改分区呢？上恩山找找教程。AdGuardHome 和 ShellCrash 都各占存储空间 11M 左右。

**Comment by NJYZ-96** [comment]
> 这路由器的分区也是 6（_/data_ 目录太小了），试试改分区呢？上恩山找找教程。AdGuardHome 和 ShellCrash 都各占存储空间 11M 左右。

唉，我也很无语，机器配置蛮好，512m闪存呢，结果/data 目录就只给你9.4m

**Comment by DustinWin** [comment]
> > 这路由器的分区也是 6（_/data_ 目录太小了），试试改分区呢？上恩山找找教程。AdGuardHome 和 ShellCrash 都各占存储空间 11M 左右。
> 
> 唉，我也很无语，机器配置蛮好，512m闪存呢，结果/data 目录就只给你9.4m

所以上恩山找找看有没有分区方法，这路由器也不能查 U 盘。🥲

**Comment by gzxiexl** [comment]
/data/other_vol 下有100多 M
