### ISSUE TITLE
singbox dns文档只有reverse_mapping没有mapping_override

### ISSUE THREAD

**Issue by suikastar** [DustinWin/clash_singbox-tutorials#32]
https://sing-box.sagernet.org/zh/configuration/dns/#reverse_mapping

[本教程](https://github.com/DustinWin/clash_singbox-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/sing-box/%E8%BF%9B%E9%98%B6%E7%AF%87/sing-box%20PuerNya%20%E7%89%88%E5%86%85%E6%A0%B8%E9%85%8D%E7%BD%AE%20DNS%20%E4%B8%8D%E6%B3%84%E9%9C%B2%E6%95%99%E7%A8%8B-ruleset%20%E6%96%B9%E6%A1%88.md#%E5%9B%9B-dns-%E9%85%8D%E7%BD%AE)中"mapping_override": true怎么理解

**Comment by DustinWin** [comment]
我明确标明了“所有 sing-box 相关教程都是基于 sing-box PuerNya 版内核”。  
![QQ截图20240626143018](https://github.com/DustinWin/clash_singbox-tutorials/assets/45238096/f8d82d96-2fdd-43a7-a594-0c4521681357)

**Comment by suikastar** [comment]
> 我明确标明了“所有 sing-box 相关教程都是基于 sing-box PuerNya 版内核”。 ![QQ截图20240626143018](https://private-user-images.githubusercontent.com/45238096/343033843-f8d82d96-2fdd-43a7-a594-0c4521681357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY1MzgsIm5iZiI6MTcxOTM4NjIzOCwicGF0aCI6Ii80NTIzODA5Ni8zNDMwMzM4NDMtZjhkODJkOTYtMmZkZC00M2E3LWE1OTQtMGM0NTIxNjgxMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYzdiY2I5MmQwZGNhNTRhMmU3ZGEyNjFkYjYyZDFkMDIzY2Q3NDgwMzNmYTAzNjE4NTBlNGEzMzU0NWU4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wu76EVD3VvWdVAX5m1iLoK97B8iWJYstoPPCd__V3no)

https://github.com/search?q=owner%3APuerNya+mapping&type=code

去PuerNya也找到不相关配置，能科普一下这个参数作用吗，谢谢

**Comment by DustinWin** [comment]
> > 我明确标明了“所有 sing-box 相关教程都是基于 sing-box PuerNya 版内核”。 ![QQ截图20240626143018](https://private-user-images.githubusercontent.com/45238096/343033843-f8d82d96-2fdd-43a7-a594-0c4521681357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY1MzgsIm5iZiI6MTcxOTM4NjIzOCwicGF0aCI6Ii80NTIzODA5Ni8zNDMwMzM4NDMtZjhkODJkOTYtMmZkZC00M2E3LWE1OTQtMGM0NTIxNjgxMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYzdiY2I5MmQwZGNhNTRhMmU3ZGEyNjFkYjYyZDFkMDIzY2Q3NDgwMzNmYTAzNjE4NTBlNGEzMzU0NWU4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wu76EVD3VvWdVAX5m1iLoK97B8iWJYstoPPCd__V3no)
> 
> https://github.com/search?q=owner%3APuerNya+mapping&type=code
> 
> 去PuerNya也找到不相关配置，能科普一下这个参数作用吗，谢谢

该内核的 docs 在这里 https://github.com/PuerNya/sing-box/tree/building/docs/configuration

**Comment by suikastar** [comment]
> > > 我明确标明了“所有 sing-box 相关教程都是基于 sing-box PuerNya 版内核”。 ![QQ截图20240626143018](https://private-user-images.githubusercontent.com/45238096/343033843-f8d82d96-2fdd-43a7-a594-0c4521681357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY1MzgsIm5iZiI6MTcxOTM4NjIzOCwicGF0aCI6Ii80NTIzODA5Ni8zNDMwMzM4NDMtZjhkODJkOTYtMmZkZC00M2E3LWE1OTQtMGM0NTIxNjgxMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYzdiY2I5MmQwZGNhNTRhMmU3ZGEyNjFkYjYyZDFkMDIzY2Q3NDgwMzNmYTAzNjE4NTBlNGEzMzU0NWU4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wu76EVD3VvWdVAX5m1iLoK97B8iWJYstoPPCd__V3no)
> > 
> > 
> > https://github.com/search?q=owner%3APuerNya+mapping&type=code
> > 去PuerNya也找到不相关配置，能科普一下这个参数作用吗，谢谢
> 
> 该内核的 docs 在这里 https://github.com/PuerNya/sing-box/tree/building/docs/configuration

好的，这下清楚了
