### ISSUE TITLE
singbox教程是否可以新增【使用EDNS查询优化小众国内域名解析相关】相关内容

### ISSUE THREAD

**Issue by suikastar** [DustinWin/clash_singbox-tutorials#33]
以下节选自[官方支持](https://sing-box.sagernet.org/manual/proxy/client/#__tabbed_2_2)
```
"rules": [{
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "rule_set": "geosite-geolocation-!cn",
            "invert": true
          },
          {
            "rule_set": "geoip-cn"
          }
        ],
        "server": "google",
        "client_subnet": "114.114.114.114/24" // Any China client IP address
}]
```

原理：
1.当8.8.8.8给出的结果在geoip-cn范围内，采用此结果，因为这个ip距离使用者地理位置更近；
2.当8.8.8.8给出的结果不在geoip-cn范围内，不采用此结果，因为这个ip大概率后面要走代理，这个ip距离vps机房不是最优的。

**Comment by DustinWin** [comment]
这类配置不会写到“基础篇”和“进阶篇”里，我目前用的 sing-boxp 内核的 `fallback_rules` 配置项，有兴趣可以看“分享篇”

**Comment by suikastar** [comment]
> 这类配置不会写到“基础篇”和“进阶篇”里，我目前用的 sing-boxp 内核的 `fallback_rules` 配置项，有兴趣可以看“分享篇”

初识不知深意，再看醍醐灌顶
