### ISSUE TITLE
sing-box PuerNya版 proxy-providers 疑问 

### ISSUE THREAD

**Issue by KisThFir** [DustinWin/clash_singbox-tutorials#36]
如何定义exclude-type

**Comment by DustinWin** [comment]
《基础篇》里就有，有注释。

**Comment by KisThFir** [comment]
> 《基础篇》里就有，有注释。

"excludes": "高倍|×10"
👆🏻这个吗，排除ss类型怎么写✍🏻

**Comment by DustinWin** [comment]
> > 《基础篇》里就有，有注释。
> 
> "excludes": "高倍|×10" 👆🏻这个吗，排除ss类型怎么写✍🏻

参考 https://github.com/PuerNya/sing-box/blob/building/docs/configuration/shared/filter.zh.md，通过 `types` 参数去筛选。

**Comment by KisThFir** [comment]
> > > 《基础篇》里就有，有注释。
> > 
> > 
> > "excludes": "高倍|×10" 👆🏻这个吗，排除ss类型怎么写✍🏻
> 
> 参考 https://github.com/PuerNya/sing-box/blob/building/docs/configuration/shared/filter.zh.md ，通过 `types` 参数去筛选。

![Screenshot_2024-07-04-12-45-35-78_d2ee0e1115b0a64ebff5994ebce8502f](https://github.com/DustinWin/clash_singbox-tutorials/assets/19422564/2bae5c3a-2671-4355-8837-927d6eebff30)
好像不行

**Comment by KisThFir** [comment]
小白折腾半天，实现不了全部节点排除ss类型，佬教教
@DustinWin

**Comment by KisThFir** [comment]
解决了，types里面除了ss都填上

**Comment by DustinWin** [comment]
> 解决了，types里面除了ss都填上

好的，`types` 还不支持排除。
