### ISSUE TITLE
mix内核geodata方案黑名单gfwlist好像失效了

### ISSUE THREAD

**Issue by shihaoZheng** [DustinWin/clash_singbox-tutorials#38]
参考 生成带有自定义出站和规则的 sing-box 配置文件直链-geodata 方案.md 黑名单模式设置的，发现github和youtube走的规则都是漏网之鱼。
如果使用漏网之鱼走代理会影响米家app获取设备正常状态。
如果使用白名单模式有时会使B站加载头像失败，视频网页加载非常慢。
如果使用 分享自己使用 ShellCrash（fakeip 模式）搭配 AdGuardHome 的一套配置.md 的设置，全部远程控制类的软件用不了，而且类似B站也是有时加载头像失败，视频网页加载非常慢。
现在就觉得黑名单模式起码不太影响正常国内网页的使用，但是代理这块好像有问题，麻烦大佬抽空看看了
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/6390b489-8c00-46d2-a413-f9e0fe7aa203)

**Comment by shihaoZheng** [comment]
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/12cb9a3f-4489-446b-adc6-d06a976a064d)
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/7bf29c96-92ed-4475-835a-319d68955c9f)
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/f192dc8a-e2c0-49a7-a182-3a027d6f7444)
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/cb79628d-fd97-49b1-bc1f-51f006333762)
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/e0526303-e5c7-41c8-b2fd-e19809b0f71b)
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/f6a44ead-0305-4fdc-b6b5-a2c8e6dc34a5)

**Comment by DustinWin** [comment]
你导入 geodata 规则集的方式或者命令是什么？

**Comment by DustinWin** [comment]
> curl -o $CRASHDIR/geosite.db -L https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.db curl -o $CRASHDIR/geoip.db -L https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.db

配置完全照搬只改了个订阅？

**Comment by shihaoZheng** [comment]
对，配置这里重复了
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/4843d994-f553-4797-89a0-39cd2819eb09)
‘；
使用分享自己使用 ShellCrash（fakeip 模式）搭配 AdGuardHome 的一套配置.md，这个也是配置完全照搬只改了个订阅，但是远程软件像向日葵之类的都用不了，而且漏网之鱼不代理的话各种网站感觉dns卡住一样经常加载不完全，所以还是用回mix模式，卸载删除后再根据文章全部照搬

**Comment by shihaoZheng** [comment]
广东的移动千兆网

**Comment by DustinWin** [comment]
> 分享自己使用 ShellCrash（fakeip 模式）搭配 AdGuardHome 的一套配置

已修改。你使用《分享自己使用 ShellCrash（fakeip 模式）搭配 AdGuardHome 的一套配置》这个教程的话，必须使用我的规则集，向日葵是可以用的，我将它的域名加入到 `fakeip-filter` 了。

**Comment by shihaoZheng** [comment]
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/afec6946-4d22-4d5f-b0d6-b38b54326313)
换回分享自己使用 ShellCrash（fakeip 模式）搭配 AdGuardHome 的一套配置，重新电脑后还是不行

**Comment by DustinWin** [comment]
> ![image](https://private-user-images.githubusercontent.com/70837148/347427734-afec6946-4d22-4d5f-b0d6-b38b54326313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTkyNTgsIm5iZiI6MTcyMDYxODk1OCwicGF0aCI6Ii83MDgzNzE0OC8zNDc0Mjc3MzQtYWZlYzY5NDYtNGQyMi00ZDVmLWIwZDYtYjM4YjU0MzI2MzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzNDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiM2E0YWJmZmM4NGI0ZGNkOTlmNTE5MWU1ZTZhZmZiZWQxZjE1MDdjNDA4MmIzZTAzZmU2OGY0NWUyNWY3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3uApvqsCvkaBFedahYb-isCEsQhL6lqPeBF3a1RCCIA) 换回分享自己使用 ShellCrash（fakeip 模式）搭配 AdGuardHome 的一套配置，重新电脑后还是不行

得远程了我才知道原因，我这边无法复现。

**Comment by DustinWin** [comment]
![Uploading QQ20240710-222301.png…]()

**Comment by shihaoZheng** [comment]
我尝试删除并清空向日葵数据再安装还是不行
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/70837148/90adf606-4275-48c6-94e0-7e577b6926e2)

**Comment by DustinWin** [comment]
> 我尝试删除并清空向日葵数据再安装还是不行 ![image](https://private-user-images.githubusercontent.com/70837148/347451319-90adf606-4275-48c6-94e0-7e577b6926e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjMwNzIsIm5iZiI6MTcyMDYyMjc3MiwicGF0aCI6Ii83MDgzNzE0OC8zNDc0NTEzMTktOTBhZGY2MDYtNDI3NS00OGM2LTk0ZTAtN2U1NzdiNjkyNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE0NDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNzkyYmI2MDYzMGU5ZTFmODJjNTE4MDI5NzkxMzFjYTEzOGRmMmFlYjBmMjdmMDZlZjM5YWQwZjg1ZWQ3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHqduruxLx_gZxCS4IIXEI9MIEVQBHtdSo7vtRKtl64)

提供个联系方式，我远程给你看看，用 ToDesk。

**Comment by shihaoZheng** [comment]
ToDesk能用的样子，
ToDesk设备代码:214 728 860
临时密码:s0wr4dfm
