### ISSUE TITLE
自定义配置文件校验失败

### ISSUE THREAD

**Issue by chaichai102** [DustinWin/clash_singbox-tutorials#39]
按照最新的教程clash加sing-box内核安装以后，提示FATAL[0000] decode config at /tmp/ShellCrash/jsons/cust_dns.json: dns.fakeip.exclude_rule: json: unknown field "exclude_rule"
自定义配置文件校验失败，请检查【/data/ShellCrash/jsons/dns.json】文件！
尝试使用基础配置文件启动~，请问是什么问题？

**Comment by Wil1em** [comment]
更新singbox_p版内核试试？

**Comment by DustinWin** [comment]
提醒一下，是手动去更新，不要在 ShellCrash 内更新。可以参考：https://github.com/DustinWin/clash_singbox-tools
