### ISSUE TITLE
配置geodata 方案时出现无问题

### ISSUE THREAD

**Issue by chaichai102** [DustinWin/clash_singbox-tutorials#40]
DNS 模式为 mix模式，执行curl -o $CRASHDIR/jsons/dns.json -L https://cdn.jsdelivr.net/gh/DustinWin/clash_singbox-tutorials@sing-box/geodata-mix-dns.json && $CRASHDIR/start.sh restart命令后，没有下载，最后提示curl: (28) Failed to connect to cdn.jsdelivr.net port 443 after 129371 ms: Operation timed out，请问怎么解决

**Comment by DustinWin** [comment]
说明你的网把 `cdn.jsdelivr.net` 嘎了，改成 `fastly.jsdelivr.net` 试试。

**Comment by chaichai102** [comment]
好的，我再来试试

**Comment by chaichai102** [comment]
未找到配置文件链接，请先导入配置文件！提示这个。需要先导入配置文件？我做到这一步的时候。然后开始配置这个的
![image](https://github.com/user-attachments/assets/52ac3f98-b85e-4eb4-a15b-575ebe448d3d)

**Comment by DustinWin** [comment]
> 未找到配置文件链接，请先导入配置文件！提示这个。需要先导入配置文件？我做到这一步的时候。然后开始配置这个的 ![image](https://private-user-images.githubusercontent.com/51467264/348522883-52ac3f98-b85e-4eb4-a15b-575ebe448d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDM3OTUsIm5iZiI6MTcyMDk0MzQ5NSwicGF0aCI6Ii81MTQ2NzI2NC8zNDg1MjI4ODMtNTJhYzNmOTgtYjg1ZS00ZWI0LWExNWItNTc1ZWJlNDQ4ZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA3NTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNmY4NTU4YjVkZTM1NGIyYWE0ZTIzNTU5NTIwZWRiZjUwNTUxZWNiMGJlMTY0YmYyZGViNTc3MDkzODgxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._FHC2TslMSJdDfyrhNvTSZ_6JMUxTOZEcXNrKfA5Ups)

启动服务前导入配置文件就可以了。

**Comment by chaichai102** [comment]
另外请问一下，我看到geodata 方案教程里写了搭配 AdGuardHome并将 AdGuardHome 作为上游时不要使用该方法，等到后面配置AdGuardHome会有影响吗？

**Comment by DustinWin** [comment]
> 另外请问一下，我看到geodata 方案教程里写了搭配 AdGuardHome并将 AdGuardHome 作为上游时不要使用该方法，等到后面配置AdGuardHome会有影响吗？

有影响，根据教程来。

**Comment by chaichai102** [comment]
好的，谢谢。原来根据恩山的教程配置了clash和AdGuardHome，上次更新clash导致节点都连不上了，这次全部重新弄一遍

**Comment by chaichai102** [comment]
导入了配置文件，然后点击启动后提示：获取到了配置文件【/tmp/ShellCrash/singbox_config.json】，但似乎并不包含正确的节点信息！是我的节点链接有问题？

**Comment by DustinWin** [comment]
> 导入了配置文件，然后点击启动后提示：获取到了配置文件【/tmp/ShellCrash/singbox_config.json】，但似乎并不包含正确的节点信息！是我的节点链接有问题？

贴完整配置。

**Comment by chaichai102** [comment]
> > 导入了配置文件，然后点击启动后提示：获取到了配置文件【/tmp/ShellCrash/singbox_config.json】，但似乎并不包含正确的节点信息！是我的节点链接有问题？
> 
> 贴完整配置。

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <title>MIWIFI</title>
    <link href="/xiaoqiang/web/css/bc.css" rel="stylesheet">
    <link href="/xiaoqiang/diagnosis/css/neterr.css" rel="stylesheet">
</head>
<body>
<div id="doc">
    <div class="logo">
        <img src="/xiaoqiang/diagnosis/img/logo.png">
    </div>
    <div class="mod-neterr" id="text">

    </div>
</div>
<script type="text/template" id="tplmain">
        <div class="hd">
            <img src="/xiaoqiang/diagnosis/img/ico_warn.png">
            <p>{$a}</p>
        </div>
        <div class="bd">
            <a href="/cgi-bin/luci/diagnosis" class="btn btn-dft btn-block"><span>{$b}</span></a>
        </div>
        <div class="ft">
            {$c}
        </div>
</script>
<script src="/js/jquery-1.8.3.js"></script>
<script src="/js/qwrap.js"></script>
<script>
$(function(){
    $.getJSON('/cgi-bin/luci/diagnosis/errindex', function( rsp ){
        if ( rsp.code == 0) {
            $('#text').html( $('#tplmain').html().tmpl(rsp.data) );
        }
    });
});
</script>
</body>
</html>

**Comment by chaichai102** [comment]
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <title>MIWIFI</title>
    <link href="/xiaoqiang/web/css/bc.css" rel="stylesheet">
    <link href="/xiaoqiang/diagnosis/css/neterr.css" rel="stylesheet">
</head>
<body>
<div id="doc">
    <div class="logo">
        <img src="/xiaoqiang/diagnosis/img/logo.png">
    </div>
    <div class="mod-neterr" id="text">

    </div>
</div>
<script type="text/template" id="tplmain">
        <div class="hd">
            <img src="/xiaoqiang/diagnosis/img/ico_warn.png">
            <p>{$a}</p>
        </div>
        <div class="bd">
            <a href="/cgi-bin/luci/diagnosis" class="btn btn-dft btn-block"><span>{$b}</span></a>
        </div>
        <div class="ft">
            {$c}
        </div>
</script>
<script src="/js/jquery-1.8.3.js"></script>
<script src="/js/qwrap.js"></script>
<script>
$(function(){
    $.getJSON('/cgi-bin/luci/diagnosis/errindex', function( rsp ){
        if ( rsp.code == 0) {
            $('#text').html( $('#tplmain').html().tmpl(rsp.data) );
        }
    });
});
</script>
</body>
</html>

**Comment by chaichai102** [comment]
[singbox_config.json](https://github.com/user-attachments/files/16216132/singbox_config.json)

**Comment by DustinWin** [comment]
> [singbox_config.json](https://github.com/user-attachments/files/16216132/singbox_config.json)

建议你先看文档慢慢学习吧 https://sing-box.sagernet.org/zh/
