### ISSUE TITLE
分流优化：美团外卖app图片加载问题

### ISSUE THREAD

**Issue by Wil1em** [DustinWin/clash_singbox-tutorials#43]
最近发现开启代理后美团图片加载很慢甚至无法加载，经过网络搜索后发现相关解决办法，在此分享，详见：
[美团外卖AppDebug域名分流BUG的问题](https://www.blueskyxn.com/202311/6919.html)
也可以使用adguardhome对有问题的域名进行拦截

**Comment by DustinWin** [comment]
不管是单用 ShellCrash 还是搭配使用 AdGuard Home，都可以使用 ShellCrash 的 `hosts` 功能或者 AdGuard Home 里的“DNS 重写”进行重定向，按照链接里的方法，将 `d.meituan.net` 重定向到 `dreport.meituan.net`
