### ISSUE TITLE
sing-box for Android 搭配 ruleset 方案，此配置不能访问chatgpt

### ISSUE THREAD

**Issue by starifly** [DustinWin/clash_singbox-tutorials#44]
在全局下可以访问，规则模式提示正在使用vpn

**Comment by DustinWin** [comment]
我这边没发现你说的问题。

**Comment by DustinWin** [comment]
> > 我这边没发现你说的问题。
> 
> 另外还有一些问题： 就是有些网站有时候提示dns解析不了，刷新又可以。 直播吧这个数据页面 [直播吧数据](https://m.zhibo8.com/json/paihang/v2/main.html)开了代理后打开是空的，关了代理能正常访问

按照规则，这个网站本来就是走直连的。切换代理的话有些网站可能有限制。

**Comment by starifly** [comment]
> > > 我这边没发现你说的问题。
> > 
> > 
> > 另外还有一些问题： 就是有些网站有时候提示dns解析不了，刷新又可以。 直播吧这个数据页面 [直播吧数据](https://m.zhibo8.com/json/paihang/v2/main.html)开了代理后打开是空的，关了代理能正常访问
> 
> 按照规则，这个网站本来就是走直连的（我这边直连显示“暂无数据”）。切换代理的话有些网站可能有限制。

是去广告规则影响了，注释掉访问就正常了
