### ISSUE TITLE
Tproxy模式下打开米家app内核直接巨量活动连接并爆内存

### ISSUE THREAD

**Issue by Wil1em** [DustinWin/clash_singbox-tutorials#45]
Tproxy模式下手机打开米家app，面板显示活动连接快速增加，内存占用也直线上升，活动连接无法自动结束。换成tun模式就不会
环境：sing-box_p版内核 1.10.0-alpha.29-067c81a7 + shellcrash 1.9.1beta14 dev
设备：红米ax6000 + iPhone访问米家app

**Comment by DustinWin** [comment]
建议开启绕过 CN_IP。

**Comment by Wil1em** [comment]
@DustinWin 开启了绕过CN_IP的，大佬有遇到该问题嘛，还是我自己配置的问题

**Comment by Wil1em** [comment]
好像更新了https://cdn.jsdelivr.net/gh/DustinWin/geoip@ips/cn_ipv4.txt的cnip就没有出现该问题了

**Comment by DustinWin** [comment]
> 好像更新了https://cdn.jsdelivr.net/gh/DustinWin/geoip@ips/cn_ipv4.txt 的cnip就没有出现该问题了

好的。
