### ISSUE TITLE
大佬，按你分析的配置教程配置出了点问题

### ISSUE THREAD

**Issue by ylmsn1** [DustinWin/clash_singbox-tutorials#46]
![屏幕截图 2024-08-19 051841](https://github.com/user-attachments/assets/5a3d6b85-51af-428c-abb5-43f83cc2fdfd)
就是配置到这里，改称null，就上不了网

**Comment by ylmsn1** [comment]
在X86软路由上使用的

**Comment by DustinWin** [comment]
后续操作呢？参考的哪篇教程？

**Comment by ylmsn1** [comment]
> 后续操作呢？参考的哪篇教程？

[https://github.com/DustinWin/clash_singbox-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/sing-box/%E5%88%86%E4%BA%AB%E7%AF%87/%E5%88%86%E4%BA%AB%E8%87%AA%E5%B7%B1%E4%BD%BF%E7%94%A8%20ShellCrash%20%E9%87%87%E7%94%A8%20geodata%20%E6%96%B9%E6%A1%88%E7%9A%84%E4%B8%80%E5%A5%97%E9%85%8D%E7%BD%AE.md](url) 参考这篇文章，一直按教程做下来结果就是上不了网，要是不改成null，使用默认加密dns，就可以上网，但会dns泄漏。

**Comment by Wil1em** [comment]
@ylmsn1 啥内核呀，sing-box_p内核的话dns设为null时要配置好dns.json呀

**Comment by ylmsn1** [comment]
> @ylmsn1 啥内核呀，sing-box_p内核的话dns设为null时要配置好dns.json呀

sing-box PuerNya内核，按你说的，我去看了下vi $CRASHDIR/jsons/dns.json 里面是空的，加入大佬写好的代码，再改成null就成功上网了，谢谢。

**Comment by DustinWin** [comment]
> > @ylmsn1 啥内核呀，sing-box_p内核的话dns设为null时要配置好dns.json呀
> 
> sing-box PuerNya内核，按你说的，我去看了下vi $CRASHDIR/jsons/dns.json 里面是空的，加入大佬写好的代码，再改成null就成功上网了，谢谢。

教程要看完，dns 改成 `null` 只是我强迫症的操作，但一定要编辑 dns.json 文件。

**Comment by ylmsn1** [comment]
> > > @ylmsn1 啥内核呀，sing-box_p内核的话dns设为null时要配置好dns.json呀
> > 
> > 
> > sing-box PuerNya内核，按你说的，我去看了下vi $CRASHDIR/jsons/dns.json 里面是空的，加入大佬写好的代码，再改成null就成功上网了，谢谢。
> 
> 教程要看完，dns 改成 `null` 只是我强迫症的操作，但一定要编辑 dns.json 文件。

好的，谢谢大佬
