### ISSUE TITLE
请教一下crash自动生成配置文件搭配教程使用的方法

### ISSUE THREAD

**Issue by OwnerCM** [DustinWin/clash_singbox-tutorials#47]
DustinWin大佬，我使用的外面那种Free的订阅，虽然不是特别稳但同时配置多个也能满足日常使用，有3个问题请教：
1、不想手搓配置能否通过ShellCrash -> 6 导入配置文件中生成在线配置的方式搭配你的《分享自己使用 ShellCrash 采用 ruleset 方案的一套配置.md》教程使用，实际就是替换了步骤一。
2、我使用的sbp内核，部分机场只有clash的订阅，crash通过订阅链接在线生成配置的时候是否需要加上“&flag=clash”，现在没加生成的配置在面板中没有节点。
3、我是在红米AX6000使用，但因为🐔不稳定，是否应该使用黑名单模式（其实我比较想跟大佬一样用白名单模式）? 你分享使用的配置是白名单，我是否应该手搓黑名单，我看主要区别是黑名单少了一些出站规则和路由，还有其他注意点吗？
期待大佬抽空回复，感谢！

**Comment by DustinWin** [comment]
1. 我的教程都是通过手搓的方式来设定出站和规则的，并且使用的是我的规则集
2. 实际上 sing-boxp 内核的 `outbound_providers` 也是可以通过 clash.meta 来下载订阅（我的教程就是这样）的
3. 基础篇里有黑名单模式

**Comment by OwnerCM** [comment]
> 1. 我的教程都是通过手搓的方式来设定出站和规则的，并且使用的是我的规则集
> 2. 实际上 sing-boxp 内核的 `outbound_providers` 也是可以通过 clash.meta 来下载订阅（我的教程就是这样）的
> 3. 基础篇里有黑名单模式

大佬，感谢回复，那我也不偷懒了，按您的教程手搓一个配置吧！我这种情况您建议用白名单还是黑名单？

**Comment by DustinWin** [comment]
> > 1. 我的教程都是通过手搓的方式来设定出站和规则的，并且使用的是我的规则集
> > 2. 实际上 sing-boxp 内核的 `outbound_providers` 也是可以通过 clash.meta 来下载订阅（我的教程就是这样）的
> > 3. 基础篇里有黑名单模式
> 
> 大佬，感谢回复，那我也不偷懒了，按您的教程手搓一个配置吧！我这种情况您建议用白名单还是黑名单？

流量确实少的话用黑名单，否则还是推荐用白名单。

**Comment by OwnerCM** [comment]
> > > 1. 我的教程都是通过手搓的方式来设定出站和规则的，并且使用的是我的规则集
> > > 2. 实际上 sing-boxp 内核的 `outbound_providers` 也是可以通过 clash.meta 来下载订阅（我的教程就是这样）的
> > > 3. 基础篇里有黑名单模式
> > 
> > 
> > 大佬，感谢回复，那我也不偷懒了，按您的教程手搓一个配置吧！我这种情况您建议用白名单还是黑名单？
> 
> 流量确实少的话用黑名单，否则还是推荐用白名单。

好的，大佬！我去抄你配置了
