### ISSUE TITLE
RuleSet多数已经获取不到了，是不是改了地址？我说白名单模式怎么B站都走了代理

### ISSUE THREAD

**Issue by sonderscode** [DustinWin/clash_singbox-tutorials#8]
走的ruleSet配置的白名单模式，开启的TUN，手动检查发现Rule Provider里面，规则数量大多数都是0 
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/23073985/835e21be-d24d-4851-aa7c-33da73408595)
![](https://image.hhisgg.xyz/img/2024/01/24/65b09b3573332.png)

**Comment by DustinWin** [comment]
是的，已经合并到一个项目里了，https://github.com/DustinWin/ruleset_geodata

**Comment by sonderscode** [comment]
> 是的，已经合并到一个项目里了，https://github.com/DustinWin/ruleset_geodata

好的，我就说么，检查了好多遍，学了一些网络方面的东西，怎么还是跑不通，快晕了，还好发现了

**Comment by DustinWin** [comment]
> > 是的，已经合并到一个项目里了，https://github.com/DustinWin/ruleset_geodata
> 
> 好的，我就说么，检查了好多遍，学了一些网络方面的东西，怎么还是跑不通，快晕了，还好发现了

已经稳定了，不会变了。
