### ISSUE TITLE
sing-box白名单模式无法使用

### ISSUE THREAD

**Issue by WeiYiAcc** [DustinWin/clash_singbox-tutorials#9]
你好，无法导入
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/59250484/e49390c1-bda0-4b5c-81cb-cc3e771fa8ec)
无效配置
yaml: line 159: did not find expected ',' or 'I'
无法导入，问了一下cody的gpt4，它是这么回答的：
在你提供的 JSON 代码中，有几个明显的问题需要修正：
在 JSON 的末尾，有一个多余的 k 字符。
在 rule_set 数组的最后一个对象后面，有一个多余的逗号（，），而且这个逗号是全角字符，应该是半角字符（,）。
JSON 中有两个重复的大块内容，这可能是一个复制粘贴错误。

 
![image](https://github.com/DustinWin/clash_singbox-tutorials/assets/59250484/50805da3-aee7-45f4-b28b-a47d0d99281c)
 { "port_range": 6881-6889, "🎯 全球直连"},
JSON语法中,端口范围应该写成:
{ "port_range": [6881, 6889], "outbound": "🎯 全球直连"}

我根据cody的改了，还是错误，使用的也是&flag=clash链接，是由于nekoray和Hiddify Next不是[sing-box PuerNya 版内核]吗？

**Comment by DustinWin** [comment]
> 你好，无法导入 ![image](https://private-user-images.githubusercontent.com/59250484/300221590-e49390c1-bda0-4b5c-81cb-cc3e771fa8ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDU5MzMsIm5iZiI6MTcwNjQwNTYzMywicGF0aCI6Ii81OTI1MDQ4NC8zMDAyMjE1OTAtZTQ5MzkwYzEtYmRhMC00YjVjLTgxY2ItY2MzZTc3MWZhOGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAxMzM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiODhhMTk1MDNhMDRiYjVkZWU2MTlmODQzNThiNTQwMmY5MGY0ZjJkOWM0YzQ2YmJmZjRmZmZhYjg2MGY5MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWqi0L2YvWZULihr4LN5MOWIwpEyaptYGPnFC0vTopE) 无效配置 yaml: line 159: did not find expected ',' or 'I' 无法导入，问了一下cody的gpt4，它是这么回答的： 在你提供的 JSON 代码中，有几个明显的问题需要修正： 在 JSON 的末尾，有一个多余的 k 字符。 在 rule_set 数组的最后一个对象后面，有一个多余的逗号（，），而且这个逗号是全角字符，应该是半角字符（,）。 JSON 中有两个重复的大块内容，这可能是一个复制粘贴错误。
> 
> ![image](https://private-user-images.githubusercontent.com/59250484/300222352-50805da3-aee7-45f4-b28b-a47d0d99281c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDU5MzMsIm5iZiI6MTcwNjQwNTYzMywicGF0aCI6Ii81OTI1MDQ4NC8zMDAyMjIzNTItNTA4MDVkYTMtYWVlNy00NWY0LWIyOGItYTQ3ZDBkOTkyODFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAxMzM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTY4YjE3NjhmMWQ5OGQ3N2Y1ZDJjMTRjMmE5M2JmYjkyYWVhOGUzZDg1N2Q0OTAzMmU1NGU2MzA3YTZmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4dC4Q7bkHYXB2bQSo5wp06W592A-ebOjWSIPt2MRgtM) { "port_range": 6881-6889, "🎯 全球直连"}, JSON语法中,端口范围应该写成: { "port_range": [6881, 6889], "outbound": "🎯 全球直连"}
> 
> 我根据cody的改了，还是错误，使用的也是&flag=clash链接，是由于nekoray和Hiddify Next不是[sing-box PuerNya 版内核]吗？

必须使用 PuerNya 内核。
